name: Noticeboard Dev Deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pull Repo on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zc_plugin_noticeboard/backend/notice_project
            source venv/bin/activate
            git stash
            git pull origin development
            git branch -r
            cd /var/www/zc_plugin_noticeboard/backend/notice_project
            pip3 install -r requirements.txt
            python3 manage.py migrate
            yarn

      - name: copy build to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localPath: './test_root_config/dist'
          remotePath: '/var/www/zc_plugin_noticeboard/test_root_config/dist'

      - name: copy build to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localPath: './backend/notice_project/frontend/dist'
          remotePath: '/var/www/zc_plugin_noticeboard/backend/notice_project/frontend/dist'

      - name: collect static and restart gunicorn
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zc_plugin_noticeboard/backend/notice_project
            python3 manage.py collectstatic --noinput
            cd /var/www/zc_plugin_noticeboard/backend/notice_project
            source venv/bin/activate
            /bin/sh start.sh
            gunicorn --bind 0.0.0.0:8000 noticeboard.wsgi --daemon
